const proyectos = [
  {
    id: 'S125',
    nombre: 'S 125',
    descripcion: '',
    images: [
      'Proyectos/House/S125/1',
      'Proyectos/House/S125/2',
      'Proyectos/House/S125/3',
      'Proyectos/House/S125/4',
      'Proyectos/House/S125/5',
    ],
    ambientes: '',
    baños: '',
    modulos: '',
    m2: '',
    ubicacion: '',
    categoria: 'Casa',
    segmento: 'casa',
  },
  {
    id: 'S136',
    nombre: 'S 136',
    descripcion: '',
    images: [
      'Proyectos/House/S136/1',
      'Proyectos/House/S136/2',
      'Proyectos/House/S136/3',
      'Proyectos/House/S136/4',
      'Proyectos/House/S136/5',
    ],
    ambientes: '',
    baños: '',
    modulos: '',
    m2: '',
    ubicacion: '',
    categoria: 'Casa',
    segmento: 'casa',
  },
  {
    id: 'S144',
    nombre: 'S 144',
    descripcion:
      'El proyecto integra un dormitorio principal en suite y dos dormitorios en semi-suite, dispuestos de forma estratégica para brindar privacidad. El master se ubica en un ala independiente, mientras que los otros dos dormitorios se sitúan en el extremo opuesto, enmarcando el área social.En el centro, se articula la vida diaria: living, cocina, comedor y un amplio espacio semicubierto que se conecta con la galería, el solarium y la pileta, verdadero corazón de la casa. Completan el proyecto un lavadero funcional y múltiples espacios descubiertos que amplifican la conexión con el entorno.Un hogar pensado para habitar tanto adentro como afuera, donde cada rincón invita a relajarse y crear momentos memorables.',
    images: [
      'Proyectos/House/S144/1',
      'Proyectos/House/S144/2',
      'Proyectos/House/S144/3',
      'Proyectos/House/S144/4',
      'Proyectos/House/S144/5',
      'Proyectos/House/S144/6',
      'Proyectos/House/S144/7',
      'Proyectos/House/S144/8',
      'Proyectos/House/S144/9',
      'Proyectos/House/S144/10',
    ],
    ambientes: 2,
    baños: 1,
    modulos: 3,
    m2: 144,
    ubicacion:
      'Diseñada para una familia de cinco personas, esta casa fue pensada con un claro objetivo: Hacer un espacio que vaya en armonía con la naturaleza y aprovechar las vistas.',
    categoria: 'Casa',
    segmento: 'casa',
  },
  {
    id: 'S205',
    nombre: 'S 205',
    descripcion: '',
    images: [
      'Proyectos/House/S205/1',
      'Proyectos/House/S205/2',
      'Proyectos/House/S205/3',
      'Proyectos/House/S205/4',
      'Proyectos/House/S205/5',
      'Proyectos/House/S205/6',
      'Proyectos/House/S205/7',
      'Proyectos/House/S205/8',
      'Proyectos/House/S205/9',
      'Proyectos/House/S205/10',
      'Proyectos/House/S205/11',
      'Proyectos/House/S205/12',
    ],
    ambientes: '',
    baños: '',
    modulos: '',
    m2: '',
    ubicacion: '',
    categoria: 'Casa',
    segmento: 'casa',
  },
  {
    id: 'S28',
    nombre: 'S 28',
    descripcion: '',
    images: [
      'Proyectos/House/S28/1',
      'Proyectos/House/S28/2',
      'Proyectos/House/S28/3',
      'Proyectos/House/S28/4',
      'Proyectos/House/S28/5',
      'Proyectos/House/S28/6',
    ],
    ambientes: '',
    baños: '',
    modulos: '',
    m2: '',
    ubicacion: '',
    categoria: 'Casa',
    segmento: 'casa',
  },
  {
    id: 'S45',
    nombre: 'S 45',
    descripcion: '',
    images: [
      'Proyectos/House/S45/1',
      'Proyectos/House/S45/2',
      'Proyectos/House/S45/3',
      'Proyectos/House/S45/4',
    ],
    ambientes: '',
    baños: '',
    modulos: '',
    m2: '',
    ubicacion: '',
    categoria: 'Casa',
    segmento: 'casa',
  },
  {
    id: 'S46',
    nombre: 'S 46',
    descripcion: '',
    images: [
      'Proyectos/House/S46/1',
      'Proyectos/House/S46/2',
      'Proyectos/House/S46/3',
      'Proyectos/House/S46/4',
      'Proyectos/House/S46/5',
      'Proyectos/House/S46/6',
    ],
    ambientes: '',
    baños: '',
    modulos: '',
    m2: '',
    ubicacion: '',
    categoria: 'Casa',
    segmento: 'casa',
  },
  {
    id: 'S66',
    nombre: 'S 66',
    descripcion:
      'El módulo cuenta con dos dormitorios, un baño completo y un espacio central integrado de cocina, comedor y living, con expansión hacia el exterior mediante una galería frontal. La distribución prioriza la funcionalidad y la conexión con el entorno, aprovechando el largo del terreno para generar privacidad en el fondo y orientación óptima para la entrada de luz natural.',
    images: [
      'Proyectos/House/S66/1',
      'Proyectos/House/S66/2',
      'Proyectos/House/S66/3',
      'Proyectos/House/S66/4',
      'Proyectos/House/S66/5',
      'Proyectos/House/S66/6',
    ],
    ambientes: 3,
    baños: 1,
    modulos: 1,
    m2: 66,
    ubicacion:
      'Esta vivienda de 3 ambientes fue diseñada para adaptarse a terrenos de 10 x 30 metros, una medida muy común en loteos suburbanos o de fin de semana.',
    categoria: 'Casa',
    segmento: 'casa',
  },
  {
    id: 'S68',
    nombre: 'S 68',
    descripcion:
      'Este proyecto logra un ambiente integrado de cocina, comedor y living que combina funcionalidad, estilo y muchísima luz natural.Diseñado para adaptarse al ritmo de cada día, sin perder calidez ni diseño.',
    images: [
      'Proyectos/House/S68/1',
      'Proyectos/House/S68/2',
      'Proyectos/House/S68/3',
      'Proyectos/House/S68/4',
      'Proyectos/House/S68/5',
      'Proyectos/House/S68/6',
      'Proyectos/House/S68/7',
      'Proyectos/House/S68/8',
    ],
    ambientes: 3,
    baños: 1,
    modulos: 3,
    m2: 68,
    ubicacion: 'Juan Jose C Paz, Argentina',
    categoria: 'Casa',
    segmento: 'casa',
  },
  {
    id: 'S91',
    nombre: 'S 91',
    descripcion:
      'En este caso, se trata de una familia de 4 que quería, por sobre todas las cosas, aprovechar el exterior y la conexión con la naturaleza. Es por eso que creamos un amplio espacio de galería con pileta y un sector adicional de terraza tipo solarium con jacuzzi en todo el sector superior. Además, nos comentaron que para ellos era fundamental contar con mucha presencia de luz natural y ventanales, logrando espacios abiertos y aprovechando al máximo la vista.',
    images: [
      'Proyectos/House/S91/1',
      'Proyectos/House/S91/2',
      'Proyectos/House/S91/3',
    ],
    ambientes: 3,
    baños: 2,
    modulos: 3,
    m2: 91,
    ubicacion:
      'Acompañanos a recorrer el exterior de este hermoso proyecto, compuesto de 3 módulos integrados con una superficie cubierta de 91 m2.',
    categoria: 'Casa',
    segmento: 'casa',
  },
  {
    id: 'S95',
    nombre: 'S 95',
    descripcion: '',
    images: ['Proyectos/House/S95/1', 'Proyectos/House/S95/2'],
    ambientes: '',
    baños: '',
    modulos: '',
    m2: '',
    ubicacion: '',
    categoria: 'Casa',
    segmento: 'casa',
  },
  {
    id: 'AEROPUERTOS_ARGENTINA',
    nombre: 'Aeropuertos Argentina',
    descripcion: '',
    images: [
      'Proyectos/Comerciales-Institucionales/AeropuertosArgentina/1',
      'Proyectos/Comerciales-Institucionales/AeropuertosArgentina/2',
      'Proyectos/Comerciales-Institucionales/AeropuertosArgentina/3',
      'Proyectos/Comerciales-Institucionales/AeropuertosArgentina/4',
      'Proyectos/Comerciales-Institucionales/AeropuertosArgentina/5',
      'Proyectos/Comerciales-Institucionales/AeropuertosArgentina/6',
      'Proyectos/Comerciales-Institucionales/AeropuertosArgentina/7',
      'Proyectos/Comerciales-Institucionales/AeropuertosArgentina/8',
    ],
    ambientes: '',
    baños: '',
    modulos: '',
    m2: '',
    ubicacion: '',
    categoria: 'Comercial',
    segmento: 'comercial',
  },
]

export default proyectos
