// data/proyectos.js
const proyectos = [
  {
    id: 'S66',
    nombre: 'S 66',
    descripcion:
      'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    images: [
      '/casas/S66/1.png',
      '/casas/S66/2.png',
      '/casas/S66/3.png',
      '/casas/S66/4.png',
      '/casas/S66/5.png',
      '/casas/S66/6.png',
      '/casas/S66/7.png',
    ],
    ambientes: 2,
    baños: 1,
    modulos: 2,
    m2: 65,
    ubicacion: 'Bariloche, Argentina',
    categoria: 'Casa',
  },
  {
    id: 'S68',
    nombre: 'S 68',
    descripcion:
      'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    images: [
      '/casas/S68/1.png',
      '/casas/S68/2.png',
      '/casas/S68/3.png',
      '/casas/S68/4.png',
      '/casas/S68/5.png',
      '/casas/S68/6.png',
      '/casas/S68/7.png',
      '/casas/S68/8.png',
    ],
    ambientes: 2,
    baños: 1,
    modulos: 3,
    m2: 65,
    ubicacion: 'Juan Jose C Paz, Argentina',
    categoria: 'Casa',
  },
  {
    id: 'S136',
    nombre: 'S 136',
    descripcion:
      'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    images: [
      '/casas/S136/2.png',
      '/casas/S136/1.png',
      '/casas/S136/3.png',
      '/casas/S136/4.png',
    ],
    ambientes: 2,
    baños: 1,
    modulos: 3,
    m2: 65,
    ubicacion: 'Juan Jose C Paz, Argentina',
    categoria: 'Casa',
  },
  {
    id: 'S144',
    nombre: 'S 144',
    descripcion:
      'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    images: [
      '/casas/S144/1.png',
      '/casas/S144/2.png',
      '/casas/S144/3.png',
      '/casas/S144/4.png',
      '/casas/S144/5.png',
      '/casas/S144/6.png',
      '/casas/S144/7.png',
      '/casas/S144/8.png',
      '/casas/S144/9.png',
      '/casas/S144/10.png',
      '/casas/S144/11.png',
    ],
    ambientes: 2,
    baños: 1,
    modulos: 3,
    m2: 65,
    ubicacion: 'Juan Jose C Paz, Argentina',
    categoria: 'Casa',
  },
  {
    id: 'S205',
    nombre: 'S 205',
    descripcion:
      'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    images: [
      '/casas/S205/1.png',
      '/casas/S205/2.png',
      '/casas/S205/3.png',
      '/casas/S205/4.png',
      '/casas/S205/5.png',
      '/casas/S205/6.png',
      '/casas/S205/7.png',
      '/casas/S205/8.png',
      '/casas/S205/9.png',
      '/casas/S205/10.png',
      '/casas/S205/11.png',
    ],
    ambientes: 2,
    baños: 1,
    modulos: 3,
    m2: 65,
    ubicacion: 'Juan Jose C Paz, Argentina',
    categoria: 'Casa',
  },
  {
    id: 'S45SenL',
    nombre: 'S 45 en L',
    descripcion:
      'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    images: [
      '/casas/45SenL/1.png',
    ],
    ambientes: 2,
    baños: 1,
    modulos: 3,
    m2: 65,
    ubicacion: 'Juan Jose C Paz, Argentina',
    categoria: 'Casa',
  },
  {
    id: 'S60SenL',
    nombre: 'S 60 en L',
    descripcion:
      'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    images: [
      '/casas/60SenL/1.png',
    ],
    ambientes: 2,
    baños: 1,
    modulos: 3,
    m2: 65,
    ubicacion: 'Juan Jose C Paz, Argentina',
    categoria: 'Casa',
  },
  {
    id: 'ProyectoCampo100m2',
    nombre: 'Proyecto campo 100 m2',
    descripcion:
      'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    images: [
      '/casas/ProyectoCampo100m2/1.png',
    ],
    ambientes: 2,
    baños: 1,
    modulos: 3,
    m2: 65,
    ubicacion: 'Juan Jose C Paz, Argentina',
    categoria: 'Casa',
  },
  
]

export default proyectos
