import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import Footer from './components/Footer'
import LoadingPage from './sections/LoadingPage'
import { icons } from 'lucide-react'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Sienna modular',
  description: 'Generated by create next app',
  icons: { icon: '/images/Logo.svg' },
}

export default function RootLayout({ children }) {
  return (
    <html lang='es'>
      <link
        rel='icon'
        href='/favicon.ico'
        type='image/<generated>'
        sizes='<generated>'
      />
      <body className={` ${inter.variable}  antialiased relative `}>
        <LoadingPage />
        <Header />
        {children}
      </body>
    </html>
  )
}
